module.exports = {
	"pages/index/index": "home_title", // 首页
	"pages/index/work": 'work_title', //工作台
	"pages/addressList/addressList": "address_Book", // 通讯录
	"pages/my/my": "my_title", // 我的
	"pages/login/login": "login", // 登录
	"pages/activityes/activityes": "community_Culture", // 小区文化
	"pages/activityDetail/activityDetail": "culture_Detail", // 文化详情
	"pages/notice/notice": "notice", // 公告
	"pages/changeCommunity/changeCommunity": "change_Community", // 切换小区
	"pages/userInfo/userInfo": "user_Info", // 个人信息
	"pages/changeLangs/changeLangs": "change_Langs", // 切换语言
	"pages/changePwd/changePwd": "change_Pwd", // 修改密码
	"pages/notice/detail/noticeDetail": "notice_Detail", // 通知页面详情
	"pages/complaintList/complaintList": "complaint_List", // 投诉受理单
	"pages/auditComplaintOrder/auditComplaintOrder": "audit_Complaint_Order", // 处理投诉单
	"pages/complaintOrderDetail/complaintOrderDetail": "complaint_Order_Detail", // 投诉单详情
	"pages/complaintOrder/complaintOrder": "complaint_Order", // 投诉录单
	"pages/floorList/floorList": "floor_List", // 选择楼栋
	"pages/unitList/unitList": "unit_List", // 选择单元
	"pages/roomList/roomList": "room_List", // 选择房屋
	"pages/repairOrder/repairOrder": "repair_Order", // 维修工单池
	"pages/repairDispatch/repairDispatch": "repair_Dispatch", // 维修待办单
	"pages/repairDetail/repairDetail": "repair_Detail", // 维修详情
	"pages/repairAdd/repairAdd": "repair_Add", // 添加记录
	"pages/inspection/inspection": "inspection", // 巡检打卡
	"pages/inspectionReexamine/inspectionReexamine": "inspection_Reexamine", // 巡检补检
	"pages/excuteInspection/excuteInspection": "excute_Inspection", // 巡检过程
	"pages/excuteOneInspection/excuteOneInspection": "excute_One_Inspection", // 执行巡检
	"pages/purchaseRequest/purchaseRequest": "purchase_Request", // 采购申请
	"pages/pOutOfStorageRequest/pOutOfStorageRequest": "out_Of_Storage_Request", // 出库申请
	"pages/purchasingSchedule/purchasingSchedule": "purchasing_Schedule", // 申请进度
	"pages/purchaseReview/purchaseReview": "purchase_Review", // 采购审核
	"pages/purchaseList/purchaseList": "purchase_List", // 选择类型
	"pages/repairHandle/repairHandle": "repair_Handle", // 订单处理
	"pages/repairDispatchFinish/repairDispatchFinish": "repair_Dispatch_Finish", // 维修已办
	"pages/appraiseRepair/appraiseRepair": "appraise_Repair", // 回访工单
	"pages/complaintFinish/complaintFinish": "complaint_Finish", // 投诉已办单
	"pages/complaintHandle/complaintHandle": "complaint_Handle", // 投诉处理
	"pages/roomDetail/roomDetail": "room_Detail", // 房产信息
	"pages/selectFloor/selectFloor": "select_Floor", // 选择楼栋
	"pages/selectUnit/selectUnit": "select_Unit", // 选择单元
	"pages/selectRoom/selectRoom": "select_Room", // 选择房屋
	"pages/feeDetail/feeDetail": "fee_Detail", // 费用详情
	"pages/fee/roomPayFee": "room_Pay_Fee", // 收银台
	"pages/meterReading/meterReading": "meter_Reading", // 水电抄表
	"pages/addmeter/addmeter": "add_Meter", // 抄表
	"pages/applyRoom/applyRoom": "apply_Room", // 空置房
	"pages/applyRoomDetail/applyRoomDetail": "apply_Room_Detail", // 空置房详情
	"pages/applyRoomRecord/applyRoomRecord": "apply_Room_Record", // 空置房跟踪记录
	"pages/applyRoomRecordHandle/applyRoomRecordHandle": "apply_Room_Record_Handle", // 添加跟踪记录
	"pages/applyRoomRecordDetail/applyRoomRecordDetail": "apply_Room_Record_Detail", // 跟踪记录详情
	"pages/roomRenovation/roomRenovation": "room_Renovation", // 装修记录
	"pages/roomRenovationDetail/roomRenovationDetail": "room_Renovation_Detail", // 装修详情
	"pages/roomRenovationRecord/roomRenovationRecord": "room_Renovation_Record", // 跟踪记录
	"pages/roomRenovationRecordHandle/roomRenovationRecordHandle": "room_Renovation_Record_Handle", // 添加跟踪记录
	"pages/roomRenovationRecordDetail/roomRenovationRecordDetail": "room_Renovation_Record_Detail", // 跟踪记录详情
	"pages/fee/payFeeByQrCode": "pay_Fee_By_QrCode", // 请扫二维码支付
	"pages/resourceStoreManage/resourceStoreManage": "resource_Store_Manage", // 我的物品
	"pages/resource/purchaseApplyManage": "purchase_Apply_Manage", // 采购申请
	"pages/resource/addPurchaseApply": "add_Purchase_Apply", // 采购申请
	"pages/resource/purchaseApplyAuditOrders": "purchase_Apply_Audit_Orders", // 采购审批
	"pages/resource/itemOutManage": "item_Out_Manage", // 物品领用
	"pages/resource/addItemOut": "add_Item_Out", // 领用申请
	"pages/resource/itemOutAuditOrders": "item_Out_Audit_Orders", // 领用审批
	"pages/resource/itemOutDo": "item_Out_Do", // 物品发放
	"pages/resource/itemEnterDo": "item_Enter_Do", // 物品入库
	"pages/resource/allocationStorehouseManage": "allocation_Storehouse_Manage", // 调拨列表
	"pages/resource/allocationStorehouseApply": "allocation_Storehouse_Apply", // 物品调拨
	"pages/resource/allocationStorehouseAuditOrders": "allocation_Storehouse_Audit_Orders", // 调拨审批
	"pages/resource/allocationStorehouseApplyDetail": "allocation_Storehouse_Apply_Detail", // 调拨详情
	"pages/resourceStoreReturn/resourceStoreReturn": "resource_Store_Return", // 物品退还
	"pages/resourceStoreScrap/resourceStoreScrap": "resource_Store_Scrap", // 物品损耗
	"pages/resourceStoreTransfer/resourceStoreTransfer": "resource_Store_Transfer", // 物品转赠
	"pages/inspectionTransfer/inspectionTransfer": "inspection_Transfer", // 任务流转
	"pages/urgentPurchaseApplyStep/urgentPurchaseApplyStep": "urgent_Purchase_Apply_Step", // 紧急采购
	"pages/resource/purchaseApplyDetail": "purchase_Apply_Detail", // 申请详情
	"pages/hcWebView/hcWebView": "", // (empty)
	"pages/oaWorkflow/oaWorkflow": "oa_Workflow", // OA流程
	"pages/newOaWorkflowForm/newOaWorkflowForm": "new_Oa_Workflow_Form", // 起草流程
	"pages/newOaWorkflowFinish/newOaWorkflowFinish": "new_Oa_Workflow_Finish", // 流程已办
	"pages/newOaWorkflowUndo/newOaWorkflowUndo": "new_Oa_Workflow_Undo", // 流程待办
	"pages/newOaWorkflowDetail/newOaWorkflowDetail": "new_Oa_Workflow_Detail", // 待办处理
	"pages/newOaWorkflowUndoAudit/newOaWorkflowUndoAudit": "new_Oa_Workflow_Undo_Audit", // 流程审核
	"pages/newOaWorkflowFormEdit/newOaWorkflowFormEdit": "new_Oa_Workflow_Form_Edit", // 表单修改
	"pages/excuteOneQrCodeInspection/excuteOneQrCodeInspection": "excute_One_QrCode_Inspection", // 二维码巡检
	"pages/repairHandle/selectResource": "select_Resource", // 选择物品
	"pages/appointment/appointment": "appointment", // 预约核销
	"pages/appointment/hou_one": "hou_One", // 核销扫码
	"pages/maintainance/maintainance": "maintainance", // 设备保养
	"pages/maintainance/excuteMaintainance": "excute_Maintainance", // 保养
	"pages/maintainance/excuteOneMaintainance": "", // (empty)
	"pages/maintainance/maintainanceTransfer": "", // (empty)
	"pages/inspection/inspectionTodayReport": "inspection_Today_Report", // 今日巡检
	"pages/inspection/staffNoInspection": "staff_No_Inspection", // 员工未巡检
	"pages/coupon/writeOffCoupon": "write_Off_Coupon", // 核销优惠券
	"pages/coupon/writeOffIntegral": "", // (empty)
	"pages/coupon/wirteOffReserve": "write_Off_Reserve", // 核销预约
	"pages/itemRelease/itemRelease": "release_of_goods", // 物品放行
	"pages/itemRelease/itemReleaseDetail": "", // (empty)
	"pages/visit/visit": "visitors_to_do", // 訪客待辦
	"pages/visit/visitDetail": "visitDetail", // (empty)
	"pages/audit/undoAudit": "undo_Audit", // 待办审核
	"pages/resource/editPurchaseApply": "edit_Purchase_Apply", // 修改采购
	"pages/resource/allocationEnterDo": "allocation_Enter_Do", // 调拨
	"pages/report/dataReport": "data_Report", // 数据统计
	"pages/report/reportPayFeeDetail": "report_Pay_Fee_Detail", // 缴费明细表
	"pages/report/reportRoomFee": "report_Room_Fee", // 房屋费用明细
	"pages/report/reportFeeSummary": "report_Fee_Summary", // 费用汇总表
	"pages/my/staffDetailAttendance": "staff_Detail_Attendance", // 员工考勤
	"pages/car/ownerCar": "owner_Car", // 业主车辆
	"pages/report/openDoorLog": "open_Door_Log", // 开门记录
	"pages/report/chargeMachineOrder": "charge_Machine_Order", // 充电桩订单
	"pages/fee/oweFeeCallable": "owe_Fee_Callable", // 催缴登记
	"pages/fee/writeOweFeeCallable": "write_Owe_Fee_Callable", // 催缴登记
	"pages/owner/owner": "owner", // 业主
	"pages/owner/addOwner": "", // (empty)
	"pages/car/barrierGate": "barrier_Gate", // 道闸
	"pages/car/carInParkingArea": "car_In_Parking_Area", // 手工进场
	"pages/car/carOutParkingArea": "car_Out_Parking_Area", // 手工出场
	"pages/owner/editOwner": "edit_Owner", // 修改业主
	"pages/fee/createFee": "create_Fee", // 创建费用
	"pages/work/startWork": "start_Work", // 发工作单
	"pages/work/workDetail": "work_Detail", // 工作单详情
	"pages/work/workTask": "", // (empty)
	"pages/work/editWrok": "edit_Work", // 修改工作单
	"pages/work/doWork": "do_Work", // 办理工作单
	"pages/work/doWorkAudit": "do_Work_Audit", // 办理工作单
	"pages/work/copyWork": "copy_Work", // 抄送工作单
	"pages/work/doCopyWork": "do_Copy_Work", // 已阅
	"pages/complaintOrderDetail/replyComplainAppraise": "reply_Complain_Appraise", // 回复评价
	"pages/repairOrder/replyRepairAppraise": "", // (empty)
	"pages/car/barrierVideo": "" // (empty)
}